_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "configs/R-50.pkl"
  PIXEL_MEAN: [98.46033269, 96.5276075 , 94.402954]
  PIXEL_STD: [74.32064206, 77.11526937, 79.15820709]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [8, 16, 32, 64, 128 ]]"]
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "FrozenBN"
    STRIDE_IN_1X1: True
  RETINANET:
    NUM_CLASSES: 7
    SMOOTH_L1_LOSS_BETA: 1.0
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (600, 600)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN_SAMPLING: "range"
DATASETS:
  TRAIN: ('Malaga_train',)
  TEST: ('Malaga_test',)
DATALOADER:
  NUM_WORKERS: 4
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 817
  BASE_LR: 0.001
  STEPS: (40850, 49020)
  MAX_ITER: 81700
  WARMUP_ITERS: -1