_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "./configs/R-50.pkl"
  PIXEL_MEAN: [98.46033269, 96.5276075 , 94.402954]
  PIXEL_STD: [1, 1, 1]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512]]"]
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "FrozenBN"
    STRIDE_IN_1X1: False
  RETINANET:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    NUM_CLASSES: 7
    SMOOTH_L1_LOSS_BETA: 0.1
    SCORE_THRESH_TEST: 0.05
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (400, 400)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN_SAMPLING: "range"
DATASETS:
  TRAIN: ('Malaga_train',)
  TEST: ('Malaga_test',)
DATALOADER:
  NUM_WORKERS: 4
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 3268
  BASE_LR: 0.00001
  STEPS: (52288, )
  MAX_ITER: 163400
  WARMUP_ITERS: -1
TEST:
  EVAL_PERIOD: 3268
  AUG:
    "ENABLED": False
    MIN_SIZES : (400, 400)
    MAX_SIZE: 800
    FLIP: False