_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "configs/R-50.pkl"
  PIXEL_MEAN: [98.46033269, 96.5276075 , 94.402954]
  PIXEL_STD: [74.32064206, 77.11526937, 79.15820709]
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "BN"
  RETINANET:
    NUM_CLASSES: 7
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (600, 600)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN_SAMPLING: "range"
DATASETS:
  TRAIN: ('Malaga_train',)
  TEST: ('Malaga_val',)
DATALOADER:
  NUM_WORKERS: 4
  FILTER_EMPTY_ANNOTATIONS: False
SOLVER:
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 817
  BASE_LR: 0.01
  STEPS: (21775, 40850)
  MAX_ITER: 61275
  WARMUP_ITERS: -1